### ISSUE TITLE
Awkward `color` option behavior

### ISSUE THREAD

**Issue by lukasmalkmus** [briandowns/spinner#103]
I kinda like how configuring a spinner works, but setting a color is awkward. While the usage is documented and states, that the spinner is restarted with the given color, this is kinda awkward when using it in a constructor:

``` go
// This spinner starts right away:
sp := spinner.New(
	spinner.CharSets[11],
	time.Millisecond*100,
	spinner.WithColor("green"),
)
```

Maybe this should be revisited since the default state of a spinner should be stopped.

**Comment by briandowns** [comment]
Latest release removes the restart. https://github.com/briandowns/spinner/releases/tag/v1.12

**Comment by lukasmalkmus** [comment]
Guess this can be closed? Latest release seemed to work fine 👍
