### ISSUE TITLE
Colored spinner can not be restarted

### ISSUE THREAD

**Issue by lukasmalkmus** [briandowns/spinner#104]
The following code won't work for me (iTerm2 + zsh):

```go
package main

import (
	"time"

	"github.com/briandowns/spinner"
)

func main() {
	sp := spinner.New(
		spinner.CharSets[11],
		time.Millisecond*100,
		spinner.WithColor("green"),
	)
	sp.Stop()

	time.Sleep(time.Second * 1)

	sp.Start()
	defer sp.Stop()

	time.Sleep(time.Second * 5)
}
```

This code demonstrates an issue I already documented in #103. I need to call `sp.Stop()` right after creating it to stop it from starting right away. The following restart doesn't work.

It works when removing `spinner.WithColor("green")`.

**Comment by briandowns** [comment]
I'm not really pleased with the current means of configuring color. I'll see if i can push up something in the next day or two.

**Comment by briandowns** [comment]
Actually, I'm going to remove the restart call inside of the `color` method. I think that should be a reasonable stopgap for now and I'll cut a new release.
