### ISSUE TITLE
I don't want to overwrite the message after executing stop method

### ISSUE THREAD

**Issue by youngjuning** [briandowns/spinner#112]
![](https://user-images.githubusercontent.com/13204332/108591320-273b6700-73a3-11eb-9522-63e6c1d4aa6e.gif)

**Comment by briandowns** [comment]
Can you provide an example snippet of code to better understand your issue/request? Are you using the FinalMSG field?

**Comment by youngjuning** [comment]
> Can you provide an example snippet of code to better understand your issue/request? Are you using the FinalMSG field?

```go
s := spinner.New(spinner.CharSets[11], 100*time.Millisecond)
s.Suffix = " Downloading template"
s.FinalMSG = "\nInit complete!\n\nRun \"cd " + rootDir + " && yarn install && yarn start\" to enjoy it!\n"
s.Start()
...
s.Stop()
```

**Comment by mxygem** [comment]
@youngjuning Here's an implementation that I think does what you want:

```go
s := spinner.New(spinner.CharSets[11], 100*time.Millisecond, spinner.WithFinalMSG("\n\n"))
s.Suffix = " Downloading template"
s.Start()
// ...
s.Stop()
fmt.Println("Init complete!\n\nRun \"cd foo && yarn install && yarn start\" to enjoy it!")
```

**Comment by youngjuning** [comment]
@mxygem Thks bro.
