### ISSUE TITLE
Terminal is not configured properly after Ctrl+C signal 

### ISSUE THREAD

**Issue by jLopezbarb** [briandowns/spinner#122]
**Describe the bug**
When you have a spinner with the HideCursor property set to true and you stop it in the middle of execution with a Ctrl+C signal the returned terminal still has the cursor hidden.

**Expected behavior**
If a stop signal is received it should make the cursor visible.

**Comment by briandowns** [comment]
I don't really think the package should be aware of or even care of how the spinner is stopped as it could come programmatically or from the operating system. I think the best course of action would be to call the `Stop()` method on the spinner in your signal handler in your code.
