### ISSUE TITLE
Stop() doesn't clean up the current line

### ISSUE THREAD

**Issue by eugene-manuilov** [briandowns/spinner#123]
After upgrading to the latest version (from `1.13.0`) flushing stopped working for me on Ubuntu.

Here is an example:

```go
package main

import (
	"fmt"
	"time"

	"github.com/briandowns/spinner"
)

func main() {
	s := spinner.New(spinner.CharSets[9], 100*time.Millisecond)  // Build our new spinner
	s.Prefix = "prefixed: " // Prefix text before the spinner
	s.Suffix = "  :appended" // Append text after the spinner
	s.Start()                                                    // Start the spinner
	time.Sleep(4 * time.Second)                                  // Run for some time to simulate work
	s.Stop()
	fmt.Println("test")
}
```

Outputs in `v1.16.0` and in `v1.14.0` (doesn't erase the previous message):

```
prefixed: \  :appended test
```

Outputs in `v1.15.0` (still incorrect, but moves the cursor to the beginning of the line):

```
testixed: \  :appended
```

Output in `v1.13.0`:
```
test
```

**Comment by lukasmalkmus** [comment]
Can confirm!

**Comment by mirobertod** [comment]
same here

**Comment by Heyra-Joker** [comment]
can use fmt.Printf("\r") befor stop().

**Comment by dwertent** [comment]
Hi, I get the same issue, any updates?

**Comment by theckman** [comment]
Not to shill my own CLi spinner project, but my project was inspired by this one and I've been going through some of the issues here to see if mine has the same limitations. I wasn't able to reproduce this issue on mine, and wanted to see if anyone who was having this issue would be willing to give mine a go and raise an issue if you run into similar problems: https://github.com/theckman/yacspin
