### ISSUE TITLE
Is it possible to add NOTICE.txt file for legal use

### ISSUE THREAD

**Issue by Shnitzelil** [briandowns/spinner#124]

**Comment by briandowns** [comment]
What are you looking to get out of having that file added?

**Comment by Shnitzelil** [comment]
> What are you looking to get out of having that file added?

Only one thing... that our legal department will be pleased so we will be able to use this library.

**Comment by briandowns** [comment]
Added. Available in latest release.

**Comment by Shnitzelil** [comment]
@briandowns Thank you very much!
