### ISSUE TITLE
Idiomatic way to make spinner appear invisible?

### ISSUE THREAD

**Issue by vardaro** [briandowns/spinner#130]
Would like the spinner to disappear when `spinner.Stop()` is called.
Is that possible?

**Comment by briandowns** [comment]
You might be able to have the line get removed by setting `FinalMSG` with the necessary escape sequence.

**Comment by vardaro** [comment]
Hey thanks for the quick reply. Landed on something like this

```go
func (d *AppSpinner) StopAndHide() 
	a.Spinner.UpdateCharSet([]string{""})

	// Sleep until next tick so emptiness appears.
	time.Sleep(DefaultSpinnerSpeed)
	a.Spinner.Stop()
}
```
Assuming the `AppSpinner` is some struct that embeds your Spinner.
