### ISSUE TITLE
The "clear current line and reprint" doesn't work with long suffix

### ISSUE THREAD

**Issue by gbouv** [briandowns/spinner#145]
Easy repro:
```
func main() {
	suffix := "    super long string super long string super long string super long string super long string super long string super long string super long string super long string super long string super long string super long string super long string super long string super long string "
	spin := spinner.New(spinner.CharSets[11], 100*time.Millisecond, spinner.WithSuffix(suffix))
	spin.Start()
	time.Sleep(2 * time.Second)
	spin.Stop()
}
```
<img width="1601" alt="Screenshot 2022-12-02 at 15 38 42" src="https://user-images.githubusercontent.com/18011812/205317470-cc075859-42fd-49a8-8ef9-4ee2f0a67234.png">

Other side effect: we can't have multi line suffix (string with `\n`)

I think rather than clearing current line only, it should mark the location of the spinner and then erase everything between the marked location and current location.

**Comment by gbouv** [comment]
This can be "easily" fixed with the following spinner:
```
spin := spinner.New(spinner.CharSets[11], 100*time.Millisecond, spinner.WithSuffix(suffix))
spin.PreUpdate = func(s *spinner.Spinner) {
    fmt.Print("\x1B7\033[J") // save cursor position and erase everything until end of screen
}
spin.PostUpdate = func(s *spinner.Spinner) {
    fmt.Print("\x1B8")  // restore cursor position
}
```
But I would have expected the spinner to handle it by itself

**Comment by gbouv** [comment]
In fact the above "hack" doesn't even work when we start printing at the bottom of the terminal because scrolling messes up with the saved position.
So, I had to implement the actual fix of computing in advance how many lines will be needed to print the entire "spinner + suffix" string, and clearing this exact number of lines on every update in the PreUpdate function.

**Comment by briandowns** [comment]
Care to share your solution or submit a PR?

**Comment by gbouv** [comment]
Yup @briandowns I'll submit a PR and tag you on it in the next few days when I have a bit more bandwidth 👍

**Comment by gbouv** [comment]
@briandowns sorry it took so long, but the PR is up and ready for review: #146 
Let me know what you think
