### ISSUE TITLE
Running under BASH; erase() seems to backspace too many times

### ISSUE THREAD

**Issue by diddledan** [briandowns/spinner#18]
Running the example spinner from the README on a system under the BASH shell results in the spinner jumping backwards where the erase() function is backspacing more characters than are visible on the display. I can reproduce this in both Cygwin's BASH implementation and on a remote Linux system via PuTTY SSH client with BASH as the login shell on the remote system.

I double-checked and verified that this behaviour is not introduced by my previous fix for windows-support.

This may be unrelated to using BASH specifically, but more a UNIX/Posix shell issue in general.

**Comment by briandowns** [comment]
This is really interesting.  I think I'm going to need some more information.  I tested this out on Mac OSX and on Ubuntu in BASH and in ZSH and all behaved as expected.  

Are you running the code in the README with no modifications?

If you run an `env` what is your TERM var set to?

## Mac

```shell
➜  spin  zsh --version
zsh 5.0.5 (x86_64-apple-darwin14.0)
```

```shell
bash-3.2$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)
Copyright (C) 2007 Free Software Foundation, Inc.
```
## Ubuntu 

```shell
rally01% zsh --version
zsh 5.0.7 (x86_64-pc-linux-gnu)
```

```shell
bdowns@rally01:~/gocode/src/github.com/briandowns/testing/spin$ bash --version
GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by diddledan** [comment]
Just a head's up that I may not be able to get a chance to debug or report back on this until I get back from vacation, as internet will likely be non existent where I'm heading for the next two weeks.

**Comment by briandowns** [comment]
No worries.  Have fun!

**Comment by briandowns** [comment]
What systems are you doing testing on so I can reproduce what you're seeing?

**Comment by diddledan** [comment]
My test system is with windows cmd.exe and comparing against bash on the same pc via cygwin. I also noticed the issue appearing on a remote ubuntu 15.04 system (I don't have the bash version to-hand) using PuTTY-0.64 as an ssh client from http://www.chiark.greenend.org.uk/~sgtatham/putty/

Cygwin:

    $ bash --version
    GNU bash, version 4.3.39(2)-release (x86_64-unknown-cygwin)
    Copyright (C) 2013 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

**Comment by briandowns** [comment]
Seems like this behavior is unique to Putty sessions and Cygwin bash sessions.  I'm still trying to locate the actual cause.  I tested code pre and post windows support PR and it works fine pre PR.  Continuing to dig...

**Comment by diddledan** [comment]
ok, that's an interesting discovery that your tests reveal a difference in behaviour between the before and after PR cases. That would suggest that the windows-colour-compatibility is removing the ansi characters when displaying the output but retaining them in the internal representation in go-land so the number of backspaces applied to get to the beginning of the output is probably too-many by exactly the number of ansi colourcode characters.

**Comment by briandowns** [comment]
So it looks like if there's to be Windows support, we're gonna need to do a bit more reworking for full compatibility.  I'm not sure I want to reintroduce a "\r" since that was taken out in favor of a "\b" in commit e2f15158c2f7a61f45321d61a3a49a70c488c339.

**Comment by briandowns** [comment]
Windows specific issue. Reverting back to when we didn't care about windows. Will care again soon hopefully.
