### ISSUE TITLE
Provide the io.Writer

### ISSUE THREAD

**Issue by dekz** [briandowns/spinner#24]
Is it possible to provide the `io.Writer` on creation. I would like the spinner output to go to `Stderr` rather than `Stdout` so that progress can be shown while the result can be piped out.

```sh
myprog run > output.txt
⣯ Doing work
```

```sh
> cat output.txt
output from the run command
```

**Comment by briandowns** [comment]
Hi, thanks for using the package!  #25 is being tested now.

**Comment by briandowns** [comment]
Merged into master.  Give it a whirl.

**Comment by dekz** [comment]
Thanks Brian, looks good!

**Comment by briandowns** [comment]
@dekz I'd love to include your use case in the main README. Can I bother you to do a small write-up to be included?

**Comment by dekz** [comment]
How's this @briandowns ?

## Unix pipe and redirect
Setting the Spinner Writer to Stderr helps show progress to the user, with the enhancement to chain, pipe or redirect the output.

```go
  s := spinner.New(spinner.CharSets[11], 100*time.Millisecond)
  s.Suffix = " Encrypting data..."
  s.Writer = os.Stderr
  s.Start()
  // Encrypt the data into ciphertext
  fmt.Println(os.Stdout, ciphertext)
```

```sh
> myprog encrypt "Secret text" > encrypted.txt
⣯ Encrypting data...
```

```sh
> cat encrypted.txt
1243hjkbas23i9ah27sj39jghv237n2oa93hg83
```

**Comment by briandowns** [comment]
I love it.  README updated to reflect new functionality.  Thanks!
