### ISSUE TITLE
Finalised message (optional)

### ISSUE THREAD

**Issue by dekz** [briandowns/spinner#26]
I have some thoughts on a finalized string. Right now the Spinner completes and erases all that has been written.

In my code I am dealing with this myself, but it is something that might fit within this package.

### Old behaviour:
```
⣯ Encrypting data...
```
s.Stop()
```
```

### New optional Behaviour:
s.FinalMessage = "✔Data encryption successful"
```
⣯ Encrypting data...
```
s.Stop()
```
✔ Data encryption successful
```

This is useful as a checklist at the end of a long CLI command:
```
✔ Data encryption successful
✔ File uploaded to s3
⣯ Publishing...
```
Do you believe this is useful for Spinner or is something I should continue to roll my own?

**Comment by briandowns** [comment]
This is an interesting idea.  I'll have to play with it some.

**Comment by briandowns** [comment]
Did a quick mock up.  This is doable and easy. I'll push up a patch shortly.

**Comment by briandowns** [comment]
Feature complete via #27 

Example in `_examples` directory and below with as well as README


```Go
s := spinner.New(spinner.CharSets[9], 100*time.Millisecond)
s.Finally = "Complete!\nNew line!\nAnother one!\n"
s.Start()                 
time.Sleep(4 * time.Second)
s.Stop()                   
```

Output
```sh
Complete!
New line!
Another one!
```

Please let me know if this will work for you.

**Comment by briandowns** [comment]
Code and readme is fine. I'll have to update the example app.
