### ISSUE TITLE
Issues with Stop() method

### ISSUE THREAD

**Issue by Guy-Lev** [briandowns/spinner#29]
The "Stop()" method does not work properly after the major refactoring done in:
https://github.com/briandowns/spinner/commit/2f506e06238e571c76a2661aeccb7a6c005040b8

printing to the console after calling Stop(), does not clean up the line, and the spinner leaves "left overs"

Here is a short program to help reproduce:

```
package main

import (
    "github.com/briandowns/spinner"
    "sync"
    "time"
)

var m sync.Mutex
var wg sync.WaitGroup
var s = spinner.New(spinner.CharSets[14], 100*time.Millisecond)

func main() {
    s.Prefix = "Spinner Text"
    s.Start()
    for i := 0; i < 20; i++ {
        wg.Add(1)
        go printToConsole()
        time.Sleep(100 * time.Millisecond)
    }
    wg.Wait()
}
func printToConsole() {
    m.Lock()
    s.Stop()
    println("Some String...")
    s.Start()
    m.Unlock()
    wg.Done()
}
```

**Comment by briandowns** [comment]
What platform and terminal is this code running on?  Is the output from the example messed up too?

**Comment by Guy-Lev** [comment]
Yes the example I wrote will mess up the output.
I am currently running with the latest OSX:
`Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64`
Using iTerm, and oh-my-zsh.
but this also happened on all the Linux distributions I checked.

**Comment by courtneycouch** [comment]
+1 have the same issue with that update.

**Comment by saj** [comment]
#32 might fix this.

Output given the sample program above:

Before:

![screen shot 2016-11-22 at 02 18 10](https://cloud.githubusercontent.com/assets/194389/20489710/a6d0c764-b05f-11e6-979c-61f6e669e3ce.png)

After:

![screen shot 2016-11-22 at 02 46 12](https://cloud.githubusercontent.com/assets/194389/20489716/ad1a7a16-b05f-11e6-9739-64a5b7e0ccbf.png)
