### ISSUE TITLE
Does not overwrite line in sakura terminal

### ISSUE THREAD

**Issue by calebeby** [briandowns/spinner#37]
Hi guys,

Thanks for this package. It is really useful.

I recently switched from `urxvt` to [`sakura terminal`](https://launchpad.net/sakura). In `urxvt`, the spinner successfully overwrote the previous line. In `sakura`, it did not. It continuously writes new lines.

I am just beginning in `go`, but from what I can tell, the `erase` function essentially backspaces for each character in the previously printed line. Would it be better if we just used `fmt.Fprintf(s.Writer, "\033[2K")`?

`\033[2K` works in Sakura in other programs that use it.

[More info on terminal escape codes](http://unix.stackexchange.com/questions/26576/how-to-delete-line-with-echo)

If you think this would work, I can PR.

Thanks!

**Comment by briandowns** [comment]
Thank you very much for this issue.  If you want to put a PR together for testing and discussion, that'd be awesome.

**Comment by calebeby** [comment]
Huh. Running the tests in sakura, it stays on the same line. Running my project in sakura, it makes a bunch  of lines. Running my project in urxvt, it stays on the same line.

How do I use my local fork of spinner in my go project?

**Comment by briandowns** [comment]
If you've cloned it into your ${GOPATH}, you should be able to just reference it from another project.

**Comment by briandowns** [comment]
Will reopen if tests are worked on to make passing in #38
