### ISSUE TITLE
How to multiple spinners at once?

### ISSUE THREAD

**Issue by JackMordaunt** [briandowns/spinner#39]
Hi there.

Say I have 3 concurrent processes running at the same time can I have 3 spinners running at the same time, displaying one for each process? I've tried the naive approach of creating a spinner for each process but the spinners overwrite each other, competing for stdout.

Is it possible? 

Cheers!

**Comment by briandowns** [comment]
Hi @TotalSynthesis 

Great question and one I wish I could give a better answer to than, no.  It's a feature I've wanted to add for the life of the project but have never gotten around to adding it.  I can play around with it a little today to see if I can find a way to make it work.  Please let me know if you figure out a way.

You're more than welcome to submit a pull request with this functionality.
