### ISSUE TITLE
Show Spinner.FinalMSG without having to Start() and Stop()

### ISSUE THREAD

**Issue by petermbenjamin** [briandowns/spinner#44]
Thank you for this CLI spinner package.

I've used a similar CLI spinner package in node.js (https://github.com/sindresorhus/ora).
The package had some nice APIs that allowed users to use `ora` to log out messages.

For example:
- Informational messages: 
  `ora('Some info message').info()` would print out `ℹ Some info message`
  Note: doesn't require starting or stopping CLI spinner.

- Status messages:
  ```js
  progress = ora('Process started...')
  progress.start()
  // some work
  if (/*progress finished successfully*/) progress.succeed("Process successfully finished")
  else progress.failed("Process failed to complete")
  ```
  This would output
  `✔ Process successfully finished` - if successful, or
  `✖ Process failed to complete` - if failure

It would certainly be nice if this `spinner` package offered a similar API, but I'm especially interested if this package exposes a way for a user to print out informational messages without starting/stopping spinner.

**Comment by briandowns** [comment]
You can update the output safely by setting the `Suffix` or `Prefix` variables with the text you'd like without having to restart the spinner.  You can use `FinalMSG` to output a string when the spinner completes as well.  

Here's a pretty crude example: 

```go
package main

import (
	"fmt"
	"math/rand"
	"time"

	"github.com/briandowns/spinner"
)

func main() {
	s := spinner.New(spinner.CharSets[9], 100*time.Millisecond)
	s.Prefix = "Searching for evens: "
	s.Start()
	defer s.Stop()
	time.Sleep(2 * time.Second)
	var x int
	s.FinalMSG = fmt.Sprintf("Found! %d\n", x)
	for {
		if x = rand.Intn(100); x%2 == 0 {
			break
		}
		s.Suffix = fmt.Sprintf(" Odd: %d ", x)
		time.Sleep(2 * time.Second)
		continue
	}
}
```

**Comment by briandowns** [comment]
Please feel free to reopen if you're still needing assistance.
