### ISSUE TITLE
Can we have a tag or release associated with current state?

### ISSUE THREAD

**Issue by praveenkumar** [briandowns/spinner#49]
Having a tag or release (whatever current state of code) should be good so it will easy to add in glide config file. Even sha hash can be added but having a tag/release make it bit cleaner.

**Comment by briandowns** [comment]
Will this work for you? https://github.com/briandowns/spinner/releases/tag/1.0

**Comment by praveenkumar** [comment]
@briandowns Yes, Thank you. I will give it a try and then close this issue.

**Comment by budhrg** [comment]
This is working as expected with tag 1.0. This issue can be closed. Thanks

**Comment by praveenkumar** [comment]
Thanks. Closing now.

**Comment by briandowns** [comment]
You're very welcome. Please let me know if I can do anything else.
