### ISSUE TITLE
39 not working on some linux shells

### ISSUE THREAD

**Issue by saniales** [briandowns/spinner#51]
steps to reproduce:
create a spinner and start it on a linux shell
see the following

```
lllllllllllllloading message 🌍
```
instead of 
```
loading message 🌍
```

in brief, the character is not properly removed, by leaving an offset when rewriting

**Comment by briandowns** [comment]
What shell are you using?

**Comment by briandowns** [comment]
I've tested on Mint 18 with BASH and ZSH.  Please let me know the shell you're using as well as the terminal you're using.

**Comment by saniales** [comment]
I am using Ubuntu 17.04 with zsh but it does not work with any terminal on Ubuntu 17.04

**Comment by chaitan94** [comment]
I seem to have found a fix for this. Here is the modification I had made on the spinner.go file:

```go
func (s *Spinner) erase() {
	n := utf8.RuneCountInString(s.lastOutput)
	del, _ := hex.DecodeString("7f")
	for _, c := range []string{"\b", string(del), "\b"} {
		for i := 0; i < n; i++ {
			fmt.Fprintf(s.Writer, c)
		}
	}
	s.lastOutput = ""
}
```

This does make it work on my computer (Arch Linux, zsh). I haven't however tested on any other OS.

**Comment by briandowns** [comment]
Thanks @chaitan94! @saniales Any chance you can test these changes with your setup?

**Comment by chaitan94** [comment]
Can't stand this bug anymore :sweat_smile: 

I have tested this myself on Debian and Ubuntu. I have raised a pull request for this fix.
