### ISSUE TITLE
Control characters instead of spinner on Windows

### ISSUE THREAD

**Issue by pshevtsov** [briandowns/spinner#52]
It doesn't display spinner on Windows:

<img width="662" alt="spinner-windows-bug" src="https://user-images.githubusercontent.com/290451/33183186-ddae0e42-d087-11e7-8b22-7a8b9010c2e5.png">

**Comment by briandowns** [comment]
I don't have access to a windows system so if you or someone else would like to contribute a patch for this, that would be greatly appreciated.

**Comment by joerocklin** [comment]
FYI: Microsoft makes windows VMs available for free for testing purposes. They indicate it is for testing with various browser versions, but I've been able to test pretty much anything in them. 
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by schollz** [comment]
@pshevtsov You might try the PR to see if it helps for you: https://github.com/briandowns/spinner/pull/61

**Comment by briandowns** [comment]
Closing due to age and potential fix from #61
