### ISSUE TITLE
Spinner Eats Lines on CentOS 7

### ISSUE THREAD

**Issue by Otlichno** [briandowns/spinner#55]
We have this as part of our automation for tracking the status of a executing Task, and on the environments that it was created on (Macs) it works correctly were as the automation progresses each line is added with automation information and the spinner stays on the new line. On my CentOS VM the spinner causes the Task line to eat (backspace) all characters on the line that it is on, then it moves to the line above and continues until the Task line with Spinner are sitting in the top left corner. 

The Spinner type being used is #34 

Code is:
//define spinner charset and speed
spin := spinner.New(spinner.CharSets[34], 100*time.Millisecond)
spin.Prefix = "\033[?25lTask " + taskID + ": "
spin.Start()

**Comment by zorino** [comment]
Same thing with gnu screen ($TERM = screen-256color)

**Comment by Glacier759** [comment]
Same thing with gnu screen ($TERM = xterm)

**Comment by hellt** [comment]
Same experience when using putty or mobaxterm. They default to xterm terminal emulation

Any chance @briandowns you can have a look at it?

**Comment by IanCassTwo** [comment]
Same here with Putty and Debian 9

**Comment by edglynes** [comment]
https://github.com/briandowns/spinner/pull/96

**Comment by hellt** [comment]
this fixes it for me (1.11.1)
