### ISSUE TITLE
spinners not rewriting line properly in iterm2

### ISSUE THREAD

**Issue by BenTheElder** [briandowns/spinner#64]
Reported by a user (@liztio) of a tool of mine that uses spinner (thanks!)
![image](https://user-images.githubusercontent.com/917931/47454564-5f571e80-d784-11e8-8e12-c38c6d9c0ac1.png)

I installed iterm2 and found that disabling unicode 9 text width fixes this, but that option is on by default and generally something users probably want. I've not dug into this further yet.

**Comment by briandowns** [comment]
Sorry for the delay in response. Thanks for filing this. I'll take a look.

**Comment by briandowns** [comment]
Having a bit of an issue reproducing. Is this still an issue?

**Comment by BenTheElder** [comment]
Sorry I'm not using this package anymore (I am using a tiny one internal to our project with just what I needed) and I don't remember the details beyond what I posted here 😅

**Comment by briandowns** [comment]
Cool. Thanks for the update!
