### ISSUE TITLE
Spinners not spinning in OSX 10.14.3 terminal after updating to Go 1.12

### ISSUE THREAD

**Issue by dmolesUC3** [briandowns/spinner#69]
I see a lot of cursor movement, but the spinner doesn't update properly. The final result is fine, though.

**Comment by briandowns** [comment]
Can you provide the code you're executing? Is it the example? I can look at this today.

**Comment by dmolesUC3** [comment]
Thanks! I haven't tried the example. Here's the code (in context [here](https://github.com/dmolesUC3/cos/blob/master/internal/suite/case.go#L47-L69)):

```go
func (c *caseImpl) RunWithSpinner(index int, target objects.Target, dryRun bool) string {
	sp := newSpinner(c.title(index))
	sp.Start()

	elapsed, ok, detail := c.maybeExec(target, dryRun)
	if time.Duration(elapsed) < minTaskTime {
		time.Sleep(minTaskTime - time.Duration(elapsed))
	}

	sp.FinalMSG = c.finalMsg(index, ok, elapsed)
	sp.Stop()

	return detail
}

var spinChars = strings.Split(spinCharsStr, "")
var frameDuration = time.Second / time.Duration(len(spinChars))

func newSpinner(title string) *spinner.Spinner {
	sp := spinner.New(spinChars, frameDuration)
	sp.Suffix = " " + title
	return sp
}
```

**Comment by dmolesUC3** [comment]
Hmm, I thought it might be because I'm using emoji for spin characters, but I modified the example to do that and it doesn't seem to be the problem. Let me see if I can pin it down—it's going to be tricky to run my code unless you have an S3 bucket handy.

**Comment by briandowns** [comment]
What is in your `spinCharsStr` variable? I just ran the tests with Go 1.12 on Mac and it's ok. I'll dig into the lib a bit further. What's the expected return of the frameDuration? Can you print that out and make sure it's what you're expected?

**Comment by dmolesUC3** [comment]
```go
	spinCharsStr = "🌑🌒🌓🌔🌕🌖🌗🌘"
```

I don't think the choice of characters is the issue. It might be that I'm outputting something during the task that causes it to misbehave—I just modified my code to run a dummy task that just sleeps for four seconds, and didn't see the problem. I think you can close this for now and if I can pin it down with more information, I can re-open it.

**Comment by briandowns** [comment]
Sounds good. I'll close this. Please feel free to re-open if you run into any trouble. Mind if we add that character set to the library?
