### ISSUE TITLE
Expose RWMutex to lock state so that spinner doesnt output when it shouldnt

### ISSUE THREAD

**Issue by schmidtp0740** [briandowns/spinner#70]
I came across this bug where sometimes the spinner will output even after we execute Stop(). One solution I notice is if you were to expose the RWMutex. Could you expose it either making the attribute public or expose through functions?

Below is an example of what I am seeing
```
func main() {
	s := spinner.New(spinner.CharSets[22], 1*time.Microsecond)
	s.Start()
	time.Sleep(5 * time.Second)
	s.Stop()
	for i := 0; i < 10; i++ {
		fmt.Printf("hello %d\n", i)
	}
}
```

A solution might be 
```
# in github.com/briandowns/spinner
func Lock(){
 s.lock.Lock()
}

func Unlock(){
 s.lock.Unlock()
}
```
```
# in app
func main() {
	s := spinner.New(spinner.CharSets[22], 1*time.Microsecond)
	s.Start()
	time.Sleep(5 * time.Second)
	s.Stop()
        s.Lock()
	for i := 0; i < 10; i++ {
		fmt.Printf("hello %d\n", i)
	}
        s.Unlock()
}
```

**Comment by briandowns** [comment]
Thanks for filing this repo. I'll take a look at it asap. As for that short duration in the example, are you using durations that short? I'm curious if the runtime thread scheduler's behavior is to blame here. Regardless, I'm happy to make this work. Thanks again for the report!

**Comment by briandowns** [comment]
@schmidtp0740  If you're happy with https://github.com/briandowns/spinner/pull/71 I'll merge and tag a new release.

**Comment by schmidtp0740** [comment]
No, I'm not using the duration that short but it was the only way to see the behavior consistently as i am seeing this bug on only very rare occasions but they happen. Thanks for responding so quickly!

**Comment by schmidtp0740** [comment]
@briandowns That looks good to me, thanks!

**Comment by briandowns** [comment]
Master is up-to-date now and made a 1.5 release. Thanks again for the bug report!
