### ISSUE TITLE
Add Option to Hide Cursor

### ISSUE THREAD

**Issue by briandowns** [briandowns/spinner#72]
After having written the C version of this recently, the Go version should do the same.

**Comment by ivenk** [comment]
Hey @briandowns ,
I looked into this but im not really happy with my solution however I cannot think of a better one at the moment. Maybe you could tell me how you did this in C.

I tried hiding the cursor using os/exec and the command :
`tput civis` (1)
and it works fine.
Later I can bring it back using : 
`tput cvvis` (2)

However if the program exits irregularly I can not ensure that (2) is called. If that happens the cursor stays hidden even after the program terminates.

**Comment by briandowns** [comment]
I ran into the same issue with the C version. I don't really have any good answer for it other than having the caller have it reset in `Stop` or mentioning it can happen and they are responsible. Open to other suggestions.

**Comment by briandowns** [comment]
Resolved in #73 . Thanks for doing this @ivenk !
