### ISSUE TITLE
An extra space character added to the spinner line

### ISSUE THREAD

**Issue by ahmetb** [briandowns/spinner#74]
See this screenshot:

![image](https://user-images.githubusercontent.com/159209/57256850-9d26e080-700c-11e9-92b4-8110c0029b11.png)

In this example, I set:

```
s.Prefix = "[ "
s.Suffix = " ] message..."
```

however, I still get an empty space after `message...` and before the cursor indicator of my terminal emulator.

It seems like there's an extra space somewhere in the code.

**Comment by ahmetb** [comment]
Seems to be by design (as it's very apparent in the code), but I'm not sure why.

https://github.com/briandowns/spinner/blob/ac46072a5a9105597c1fd63f9e246477b116772e/spinner.go#L288

**Comment by briandowns** [comment]
It's been a number of years since that line was written and I can't honestly remember. I think it had something to do with the multibyte chars of some of the spinners overlapping the adjacent text.

**Comment by briandowns** [comment]
I think this was also due to not having the "hide cursor" feature as well. I'll push up a change that will remove the extra space.

**Comment by briandowns** [comment]
Space removed on master branch.
