### ISSUE TITLE
Tags in this repository are not recognized by Go Modules

### ISSUE THREAD

**Issue by ahmetb** [briandowns/spinner#75]
It's because the repo uses `1.6` as a tag and not `v1.6` which would be recognized by semver, or better `v1.6.0`.

If you tag the future releases properly, users with `go.mod` wouldn't end up with something like

```txt
require (
	github.com/briandowns/spinner v0.0.0-20190319032542-ac46072a5a91
    ...
```

**Comment by briandowns** [comment]
Hi @ahmetb. Thanks for reporting this. "properly" for Go mods, yes, I'll likely update how tagging is done. This repo and it's semver tags predate Go mods and I was maintaining consistency for as long as I could until someone complained.

**Comment by ahmetb** [comment]
I'd recommend just tagging new versions with the semver scheme and not delete existing tags. Alternatively, you can create new tags with v* prefix and *.0 suffix from existing tag references, too.

Thanks!

**Comment by briandowns** [comment]
That's the intent! Thanks!
