### ISSUE TITLE
update suffix and prefix in real-time

### ISSUE THREAD

**Issue by roscopecoltran** [briandowns/spinner#80]
Hi guys,

Hope you are all well !

I would like to have spinner with dynamic suffix and prefix. Is it possible ?

Cheers,
R.

**Comment by briandowns** [comment]
Hey! You can update the corresponding field on the returned spinner struct. Make sure to call lock and unlock on the struct when necessary.

**Comment by roscopecoltran** [comment]
Here is the code for tick:
https://github.com/lucmski/limo/blob/topics/cmd/webui.go#L108
https://github.com/lucmski/limo/blob/topics/output/color.go#L161-L191

Doesn't work :-(

**Comment by briandowns** [comment]
Can you provide the output and details on what's happening?

**Comment by briandowns** [comment]
I put this together to demonstrate how you can use the spinner, add a prefix mid use, and updated it and then the same for a suffix.

```go
package main

import (
	"time"

	"github.com/briandowns/spinner"
)

func main() {
	s := spinner.New(spinner.CharSets[9], time.Millisecond*400)
	s.Start()
	time.Sleep(time.Second * 4)
	s.Lock()
	s.Prefix = "Prefix: "
	s.Unlock()
	s.Restart()
	time.Sleep(time.Second * 4)
	s.Lock()
	s.Prefix = "Updated prefix: "
	s.Unlock()
	time.Sleep(time.Second * 4)
	s.Lock()
	s.Prefix = "Prefix: "
	s.Unlock()
	s.Restart()
	time.Sleep(time.Second * 4)
	s.Lock()
	s.Suffix = " Suffix"
	s.Unlock()
	time.Sleep(time.Second * 4)
	s.Lock()
	s.Suffix = " Updated suffix"
	s.Unlock()
	time.Sleep(time.Second * 4)
	s.Stop()
}
```

**Comment by briandowns** [comment]
Can this issue be closed?

**Comment by roscopecoltran** [comment]
yes, thanks for your help :-) 

Have a nice day !
