### ISSUE TITLE
"Stop()" not clearing characters properly on Windows

### ISSUE THREAD

**Issue by danawoodman** [briandowns/spinner#85]
I'm seeing some strange behavior on Windows when a spinner is stopped and then a line of text is printed.

`Starting system service...` is my spinner text.

Then in my code I do something like:

```go
s := spinner.New(/* ... */)
s.Start()

// ... do some stuff ....

s.Stop()

fmt.Println("Started system service")
```

But the output seems to get smashed together:

```
C:\>prog.exe service start
Started system servicervice...
```

See the mangled `servicervice`.

My assumption was that it didn't properly clear the line of text before printing the next line so I put a timer in but the same result occurred.

```go
s.Stop()

time.Sleep(time.Second)

fmt.Println("Started system service")
```

Is this a known issue?

**Comment by danawoodman** [comment]
@briandowns any chance you know why this might be occurring?

**Comment by danawoodman** [comment]
Ah, just found a strange workaround.

My spinner has a `Suffix` set. If I `.Stop()` the command then print out text that is **less characters than the length of the suffix + spinner than extra characters show**. If I, for example, set it up like so:

```go
s := spinner.New(/* ... */)
s.Suffix = " hello world!"
s.Start()
  
// ...do stuff

s.Stop()
fmt.Println("This is a very long message, much longer than spinner + suffix!")
```

... I don't see any extra characters show up.

But in the case where the suffix is longer than the message, I see extra characters show up from the `Suffix`:

```go
s := spinner.New(/* ... */)
s.Suffix = " some long message here"
s.Start()
  
// ...do stuff

s.Stop()
fmt.Println("short msg")
```

Seems like on Windows this causes text to not clear properly.

**Comment by briandowns** [comment]
Hmm, that's an interesting one. I don't have any windows boxes to test with but am happy to take PR's. This isn't a known issue as far as I know. I'll check around and see if anyone has a windows box they can test and submit a PR.

**Comment by danawoodman** [comment]
@briandowns you can use VirtalBox to install a Windows VM for free. Using Vagrant is helpful:

1. Install VirtualBox (free)
2. Install Vagrant (free)

Then:

```shell
mkdir my-win-box
cd my-win-box
vagrant box add gusztavvargadr/windows-10
vagrant init
```

Then edit Vagrant file to replace `config.vm.box` value with:

```
  config.vm.box = "gusztavvargadr/windows-10"
```

Then setup:

```shell
vagrant up
vagrant ssh
```

This will SSH you into your Windows machine

**Comment by briandowns** [comment]
I'm aware. Thank you however I'm still going to defer to someone that has one to do this as I'm unable to at the moment.

**Comment by akshaybabloo** [comment]
This is now happening on macOS too

**Comment by briandowns** [comment]
What terminal emulator are you using?

**Comment by akshaybabloo** [comment]
@briandowns I am on zsh. Running it on Goland and iTerm. Both seem to have the same effect.

**Comment by maxzaleski** [comment]
I second @akshaybabloo.

**Comment by theckman** [comment]
If anyone who's having this issue would have some time to try the same things on the spinner I created after experiencing similar issues, I'd really appreciate it: https://github.com/theckman/yacspin. I believe this issue may not be present in mine.

**Comment by briandowns** [comment]
@danawoodman tested on latest windows and mac and seems to be resolved at this point.
