### ISSUE TITLE
Add iota constants for spinner.CharSets

### ISSUE THREAD

**Issue by Wulfheart** [briandowns/spinner#95]
What about declaring package constants?

```golang
const (
	Arrows = iota
	BarUpDown
        SomeFancyDescriptionForNumber2
)
```

This would result in

```golang
spinner.New(spinner.CharSets[spinner.Arrows], 100*time.Millisecond)
```

**Comment by briandowns** [comment]
Thanks for filing this. I don't know what problem this is solving. I'm not opposed but I think it might introduce some oddities in naming.

**Comment by Wulfheart** [comment]
It’s just a personal preference 🙃

For me it is just inconvenient to make a number. It would be more clear if there would be an (optional) name so it can be read more quickly in contexts with multiple different spinners.

**Comment by briandowns** [comment]
Going to close for now. There may be a time where concise and descriptive names can be had and I'll entertain a proposal then. Thanks again for the suggestion!
